In [1]:
import numpy as np

In [20]:
##Q1 
math = [80,70,90,27.5,43,55,67,89,90]
science = [80,77,90,27.5,43,56,67,89,90]
english = [80,70,92,27.5,43,55,87,89,90]
it = [80,70,90,40,43,55,7,89,91]
print("highest_math : ",max(math),"\n", "lowest_math : ", min(math),"\n", "average_math : ", np.mean(math))
print("highest_science : ",max(science),"\n", "lowest_science : ", min(science),"\n", "average_science : ", np.mean(science))
print("highest_english : ",max(english),"\n", "lowest_english : ", min(english),"\n", "average_english : ", np.mean(english))
print("highest_it : ",max(it),"\n", "lowest_it : ", min(it),"\n", "average_it : ", np.mean(it))
highest_all = [max(math),max(science),max(english),max(it)]
lowest_all = [min(math),min(science),min(english),min(it)]
average_all = [np.mean(math),np.mean(science),np.mean(english),np.mean(it)]
print("highest_overall : ",max(highest_all),"lowest_overall : ",min(lowest_all),"average_overall : ",np.mean(average_all))

highest_math :  90 
 lowest_math :  27.5 
 average_math :  67.94444444444444
highest_science :  90 
 lowest_science :  27.5 
 average_science :  68.83333333333333
highest_english :  92 
 lowest_english :  27.5 
 average_english :  70.38888888888889
highest_it :  91 
 lowest_it :  7 
 average_it :  62.77777777777778
highest_overall :  92 lowest_overall :  7 average_overall :  67.48611111111111


In [25]:
##Q2
print("Enter basic salary: ")
basic_salary = int(input())

if basic_salary <= 10000:
    hra = 0.2 * 10000
    da = 0.8 * 10000
    Gross_salary = basic_salary + hra + da
    print("Gross Salary:", Gross_salary)
elif 10000 < basic_salary <= 20000:
    hra = 0.25 * 20000
    da = 0.9 * 20000
    Gross_salary = basic_salary + hra + da
    print("Gross Salary:", Gross_salary)
elif basic_salary > 20000:
    hra = 0.3 * 20000
    da = 0.95 * 20000
    Gross_salary = basic_salary + hra + da
    print("Gross Salary:", Gross_salary)
else:
    print("Invalid")


Enter basic salary: 
2500
Gross Salary: 12500.0


In [33]:
print("Enter password : ")
print("conditions : ","\n","atleast 1 letter [a-z] and 1 in [A-Z] , 1 number b/w [0-9] ","\n","atleast 1 character[$#@]","\n","min length 6 characters , max 16")
passw = input()
n = len(passw)
if 6<= n <=16:
    if any('#$@' for char in passw):
         if any(char.isupper() for char in passw):
              if any(char.islower() for char in passw):
                    print("password is valid")
              else:
                    print("atleast 1 letter from [a-z] should be there")
         else:
                print("atleast 1 letter from [A-Z] should be there")
    else:
        print("special characters not present")
else:
    print("password length not valid")

Enter password : 
conditions :  
 atleast 1 letter [a-z] and 1 in [A-Z] , 1 number b/w [0-9]  
 atleast 1 character[$#@] 
 min length 6 characters , max 16
#12jsmn
atleast 1 letter from [A-Z] should be there


In [45]:
##Q3 a
L = [10,20,30,40,50,60,70,80]
L = np.append(L,200)
L = np.append(L,300)
print(L)
indices_to_remove = np.where((L == 30) | (L == 40))
indices_to_remove

[ 10  20  30  40  50  60  70  80 200 300]


(array([2, 3], dtype=int64),)

In [43]:
##Q3 b
L = np.delete(L,2)
L = np.delete(L,3)
print(L)

[ 10  20  40  60  70  80 200 300]


In [46]:
##Q3 c 
L.sort()
print(L)

[ 10  20  30  40  50  60  70  80 200 300]


In [53]:
##Q3 d
##in descending order :
# Reverse the array in-place
L = L[::-1]
print(L)

[300 200  80  70  60  50  40  30  20  10]


In [60]:
##Q4
import pandas as pd
D = {
    1 : "One",
    2 : "Two",
    3 : "Three",
    4 : "Four",
    5 : "Five"
}
df = pd.DataFrame(D, index=[1])
df

1    2      3     4     5
1  One  Two  Three  Four  Five

In [61]:
df[6] = ['Six']
df

1    2      3     4     5    6
1  One  Two  Three  Four  Five  Six

In [81]:
import pandas as pd
D = {
    1 : "One",
    2 : "Two",
    3 : "Three",
    4 : "Four",
    5 : "Five"
}
df = pd.DataFrame(D, index=[1])
df = df.drop(2,axis=1)
df

1    1
3    1
4    1
5    1
dtype: int64

In [82]:
import pandas as pd
D = {
    1 : "One",
    3 : "Three",
    4 : "Four",
    5 : "Five"
}
df = pd.DataFrame(D, index=[1])
if 6 in df:
    print("present")
else:
    print("not present")

not present


In [83]:
import pandas as pd
D = {
    1 : "One",
    2 : "Two",
    3 : "Three",
    4 : "Four",
    5 : "Five"
}
df = pd.DataFrame(D, index=[1])
df.count()

1    1
2    1
3    1
4    1
5    1
dtype: int64

In [85]:
##Q6
import numpy as np
L = np.linspace(100,900,100,dtype=int)
L

array([100, 108, 116, 124, 132, 140, 148, 156, 164, 172, 180, 188, 196,
       205, 213, 221, 229, 237, 245, 253, 261, 269, 277, 285, 293, 302,
       310, 318, 326, 334, 342, 350, 358, 366, 374, 382, 390, 398, 407,
       415, 423, 431, 439, 447, 455, 463, 471, 479, 487, 495, 504, 512,
       520, 528, 536, 544, 552, 560, 568, 576, 584, 592, 601, 609, 617,
       625, 633, 641, 649, 657, 665, 673, 681, 689, 697, 706, 714, 722,
       730, 738, 746, 754, 762, 770, 778, 786, 794, 803, 811, 819, 827,
       835, 843, 851, 859, 867, 875, 883, 891, 900])

In [88]:
count_even = 0
count_odd = 0

import numpy as np
L = np.linspace(100,900,100,dtype=int)

for i in L:  # Corrected the loop variable to 'i'
    if i % 2 == 0:
        count_even += 1
    else:
        count_odd += 1

print("Count of even numbers:", count_even)
print("Count of odd numbers:", count_odd)

Count of even numbers: 51
Count of odd numbers: 49


In [89]:
count_prime = 0
import numpy as np
L = np.linspace(100,900,100,dtype=int)
for i in L:
    if i

SyntaxError: expected ':' (1053275168.py, line 5)

In [96]:
import modulefile.ipynb
modulefile.ci(1,0.2,3)

ModuleNotFoundError: No module named 'modulefile'

In [3]:
import numpy as np
numbers = np.linspace(100,900,100,dtype=int)
prime_count = 0

for number in numbers:
    if number > 1:
        is_prime = True
        for i in range(2, int(number**0.5) + 1):
            if number % i == 0:
                is_prime = False
                break
        if is_prime:
            prime_count += 1
print(prime_count)

17


In [4]:
class Restaurant:
    def __init__(self, name, cuisine):
        self.name = name
        self.cuisine = cuisine
    
    def open_res(self):
        print("The name is: ", self.name)
        print("The Cuisine is: ", self.cuisine)
        print("The Restaurant is open")
    
p1 = Restaurant("bestone", "indian")
p1.open_res()


The name is:  bestone
The Cuisine is:  indian
The Restaurant is open


In [5]:
class User:
    def __init__(self,first_name,last_name,age):
        self.first_name=first_name
        self.last_name=last_name
        self.age=age
    
    def describe_user(self):
        print("The first name is : ",self.first_name)
        print("The last name is : ",self.last_name)
        print("The age is : ",self.age)
    
    def greet_user(self):
        print("Good Evening Mr./Ms. ",self.first_name,self.last_name)
    
p1=User("Prathamjyot","Singh",20)
p1.describe_user()
p1.greet_user()
p2=User("Moksh","Sharma",19)
p2.describe_user()
p2.greet_user()
p3=User("Yuvraj","Singh",19)
p3.describe_user()
p3.greet_user()

The first name is :  Prathamjyot
The last name is :  Singh
The age is :  20
Good Evening Mr./Ms.  Prathamjyot Singh
The first name is :  Moksh
The last name is :  Sharma
The age is :  19
Good Evening Mr./Ms.  Moksh Sharma
The first name is :  Yuvraj
The last name is :  Singh
The age is :  19
Good Evening Mr./Ms.  Yuvraj Singh
